// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieswuxrktigvicrpcdvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imllc3d1eHJrdGlndmljcnBjZHZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMzIyMzMsImV4cCI6MjA2NzkwODIzM30.7vPDLv-NDPM56Ejvea0k-VgYloqONvMxw0Ly7CBbS8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});